services:
    php-fpm:
        build: ./docker/php-fpm
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - '9000:9000'
    nginx:
        image: nginx:latest
        working_dir: /var/www/html
        ports:
            - '8888:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
